### ISSUE TITLE
How to apply same custom org-policy to all projects in my organization?

### ISSUE THREAD

**Issue by abrignola** [azsk/ADOScanner-docs#31]
From the docs I understand the only way to get the custom org-policy is to create a Git repository in my project and to upload the files there. 

There's also the following note in the docs 

> Note: We will be treating PROJECT as a boundary to customize scanner behavior. Any customizations made will apply strictly only to the project (and its components) where the org-policy endpoint resides. We will be interchangeably using the terms 'org' and 'project'.

How can I apply the same custom policy to all projects in my organization without having to create a repo in each individual project?

**Comment by v-dpardeshi** [comment]
Yes, we can do that using the 'PolicyProject' parameter with your project name where the orgpolicy you have set up.
Run the command as follows:
Get-AzSKADOSecurityStatus -OrganizationName "<Organization name>" -PolicyProject "<Name of the project hosting organization policy with which the scan should run.>"
