### ISSUE TITLE
Run ADO Scanner on Azure DevOps Server

### ISSUE THREAD

**Issue by leandromsft** [azsk/ADOScanner-docs#55]
Hi Folks,

Is there any way to run the scanner on Azure DevOps Server (on-premise)?

Thank you!

**Comment by juhi037** [comment]
Hi @leandromsft 
We currently do not support ADO on premise server. You can use it for your Azure DevOps Web Services.

**Comment by leandromsft** [comment]
> Hi @leandromsft We currently do not support ADO on premise server. You can use it for your Azure DevOps Web Services.

Thank you for help!
