### ISSUE TITLE
Is ADOScanner still active as AzSK got sunset and replaced by AzTS ?

### ISSUE THREAD

**Issue by Anand-MSFT** [azsk/ADOScanner-docs#61]
Want to know if ADOScanner still an active initiative as its seems part of AzSK and AzSK got sunset at the end of 2021 and AzSK is now replaced by AzTS. So please provide your input, So we can suggest customers if they can use ADOScanner or if there anything new under AzTS then please suggest new replacement of ADOScanner as well.

**Comment by juhi037** [comment]
Hi @Anand-MSFT  PowerShell-based DevOps Kit (AzSK) has been sunset and moved to AzTS but that does not include ADO Scanner (AzSK.ADO module). ADO Scanner is getting updates every sprint and you can continue to use it to secure your ADO organization and project resources as mentioned [here](https://azsk.azurewebsites.net/ReleaseNotes/AzSKSunsetNotice.html)

**Comment by Anand-MSFT** [comment]
Thank you @juhi037 for your input, I got my question answer so i would like to close this issue.
