### ISSUE TITLE
how to setup Log analytics workspace in Pipeline

### ISSUE THREAD

**Issue by pshahid1** [azsk/ADOScanner-docs#62]

**Comment by juhi037** [comment]
@pshahid1 Please follow these steps to set LA workspace in pipeline based scans:
1. You need to add two variables to the pipeline: 
    - LAWSId: provide your LA workspace ID in this variable
    - LAWSSharedKey: provide your LA primary key 
    Make sure both these values are correct. To find the correct pair of LAWS Id and Key, follow the steps: Go to Azure Portal ->  Select your LAWS -> Select Agent Management under settings 
2. If you are using the ADO Scanner task in a classic build/release pipeline, check the "Send events to Log Analytics" checkbox.

**Comment by pshahid1** [comment]
thank you so much, yes that configuration helped
