### ISSUE TITLE
how to enable credscan cehck and solve this ADO Scanner controller ADO_Repository_DP_Enable_Credentials_And_Secrets_Policy

### ISSUE THREAD

**Issue by pshahid1** [azsk/ADOScanner-docs#65]
Hello,

I am getting high alert from ADO Scanner to enable "Enable policy to block pushes that contain credentials and other secrets. (ADO_Repository_DP_Enable_Credentials_And_Secrets_Policy)" but cannot find any instruction or information on how to enable this configuration. The ADO Scanner gives below information but I have no idea (and cannot find anything on google) how to get that credscan checkbox  on repository policy settings.

1. Go to Project Settings --> 2. Repositories --> 3. Select a repository --> 4. Policies --> 5. Enable 'Check for credentials and other secrets' --> 6. Incase you are not able to locate this check, it means that CredScan has not been integrated for the ADO repositories. Make sure it has been integrated in your organization.

**Comment by danielstefanescu** [comment]
Hi,
I'm facing the same dilemma: how to enable this policy?

**Comment by Maetis** [comment]
The policy is not listed in https://dev.azure.com/*your_org*/*your_project*/_apis/policy/types?api-version=7.1-preview.1

But the policy seems to exist : https://dev.azure.com/*your_org*/*your_project*/_apis/policy/types/e67ae10f-cf9a-40bc-8e66-6b3a8216956e

``` json
{
    "description": "This policy will reject pushes to a repository for files that contain credentials or secrets.",
    "_links": {
        "self": {
            "href": "https://dev.azure.com/******/***************/_apis/policy/types/e67ae10f-cf9a-40bc-8e66-6b3a8216956e"
        }
    },
    "id": "e67ae10f-cf9a-40bc-8e66-6b3a8216956e",
    "url": "https://dev.azure.com/******/****************/_apis/policy/types/e67ae10f-cf9a-40bc-8e66-6b3a8216956e",
    "displayName": "Secrets scanning restriction"
}
```

If you try to add this policy to your configurations by using the API https://dev.azure.com/*your_org*/*your_project*/_apis/policy/configurations?api-version=7.1-preview.1, you will get the following message :

``` json
{
    "$id": "1",
    "innerException": null,
    "message": "Type with id 'e67ae10f-cf9a-40bc-8e66-6b3a8216956e' does not exist.",
    "typeName": "Microsoft.TeamFoundation.Policy.Server.PolicyTypeNotFoundException, Microsoft.TeamFoundation.Policy.Server",
    "typeKey": "PolicyTypeNotFoundException",
    "errorCode": 0,
    "eventId": 3000
}
```

**Comment by Maetis** [comment]
I also tried with the Terraform provider for Azure DevOps, but I wasn't able to set this policy.

[See the documentation](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/repository_policy_check_credentials)

**Comment by juhi037** [comment]
Hello all! Apologies for the inactivity on this thread. It seems that currently "CredScan for repos" is applicable only to repos internal to Microsoft. We will ensure to update the documentation to clear this confusion. We will also check if there is a way for external customers to integrate this into their ADO orgs and keep you updated with any findings.
