### ISSUE TITLE
Azure DevOps (ADO) Security Scanner - pipeline task fails

### ISSUE THREAD

**Issue by danielstefanescu** [azsk/ADOScanner-docs#71]
Hi, I've setup a pipeline with the ADO task to scan the current organization from a Microsoft-hosted agent (windows-latest) then I get the below error:
_Organization not found: Incorrect organization name or account does not have necessary permission to access the organization. Use -ResetCredentials parameter in command to login with another account_

Full log in the attachment:
[azsk-task-log.txt](https://github.com/azsk/ADOScanner-docs/files/9715056/azsk-task-log.txt)

**Comment by v-dpardeshi** [comment]
Apologies for the inactivity on this thread. Due to some access permission changes in the devops apis, the custom PAT token is not supported for scanning. We are trying to figure out the solution. Intermittent use full access token to run the scan.
