### ISSUE TITLE
Error: Attestation Denied

### ISSUE THREAD

**Issue by UA33240** [azsk/ADOScanner-docs#72]
I'm running into an issue with committing my Attestation for my Organization ADO Security Scan.  I've verified that I'm a project collection administrator at the organization level as well as the project administrator in the Attestation Host Project.  The repository I've created in my host project is called ADOScannerAttestation.  Are there permissions or a setting that I'm missing?

![image](https://user-images.githubusercontent.com/115804996/223730356-5e111dbf-b1a1-404a-9489-4e878bb38972.png)

**Comment by tmcclell** [comment]
Folks any proposed resolution to this issue?

**Comment by v-dpardeshi** [comment]
It seems that the command is reverting to the OneITVSO policy repository with the 'master' branch name. We need to run the additional command below before running the attestation command:
$env:OrgPolicyBranchName = 'main'

Please refer below link for details. 
[ADO Security Scanner for MS Digital - Overview (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoftit.visualstudio.com%2FOneITVSO%2F_wiki%2Fwikis%2FOneITVSO.wiki%2F15868%2FADO-Security-Scanner-for-MS-Digital%3Fanchor%3Dhow-can-we--add-the-resources-as-in-exception%253F&data=05%7C01%7Cv-dpardeshi%40microsoft.com%7Cd557e8c17ab2486b982808db9d935556%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638277028398628999%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KGZEfozY0m6ENuSK674UHleRLFIE9gtjJX0Xf4ZU5Lg%3D&reserved=0)
