### ISSUE TITLE
old az.resource 2.0.1 always got installed to Windows service account profile directory  NetworkService account folder, which blocks az.ps V5 task.

### ISSUE THREAD

**Issue by QiuyongWang** [azsk/ADOScanner-docs#77]
Hi ADOScanner Dev Team, we received premier enterprise customer support request and can also reproduced this issue symptom.

**Issue Symptom**
On one self-hosted agent Windows machine, the agent is registered as Windows Service underneath the NetworkService account.

One pipeline only running this single ADOScanner task always gets the old az.resource 2.0.1 module installed o Windows service account profile directory  NetworkService account folder, which blocks az.ps V5 task.

Another pipeline running az.ps v5 task will always get blocked due to this old az.resource 2.0.1 module.

I noticed the last updated date was 2022-09-29(from the market place this task page), is this ADOScanner task seems kind of in idle status in development to keep up with the latest ADO service releases? (https://marketplace.visualstudio.com/items?itemName=azsdktm.ADOSecurityScanner&ssr=false#overview)

**Comment by v-dpardeshi** [comment]
Apologies for the inactivity on this thread. Currently, there is no active development happening in the ADO scanner extension, but we plan to update it soon. We will notify you if we release a new version.
