### ISSUE TITLE
Reports not getting populated in dashboard.

### ISSUE THREAD

**Issue by apr138** [azsk/ADOScanner-docs#79]
In pipeline extension logs, i could see reports getting send to the extension data. But the dashboard not able to retrieve the same? What could be the issue?

**Comment by v-dpardeshi** [comment]
Have you created an organization-level or project-level summary dashboard? And are you encountering any errors? If so, could you please share a screenshot?

**Comment by apr138** [comment]
This issue is with special character used in the project name.
