### ISSUE TITLE
Cannot find an overload for "PlatformParameters" and the argument count: "1".

### ISSUE THREAD

**Issue by wi-ry** [azsk/ADOScanner-docs#8]
When attempting to run this utility, I run into the following error:
`Get-AzSKADOSecurityStatus -OrganizationName "test" -ProjectNames "Test"`

```
New-Object: D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Helpers\ContextHelper.ps1:47
Line |
  47 |  … arameters = New-Object Microsoft.IdentityModel.Clients.ActiveDirector …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "PlatformParameters" and the argument count: "1".


StackTrace: at GetCurrentContext, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Helpers\ContextHelper.ps1: line 47
at GetCurrentContext, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Helpers\ContextHelper.ps1: line 16
at SetContext, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Helpers\ContextHelper.ps1: line 126
at AzSKRoot, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Abstracts\AzSKRoot.ps1: line 34
at SVTResourceResolver, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\Framework\Core\SVT\SVTResourceResolver.ps1: line 46
at Get-AzSKADOSecurityStatus<Process>, D:\Documents\PowerShell\Modules\AzSK.ADO\1.3.0\SVT\SVT.ps1: line 333
at <ScriptBlock>, <No file>: line 1
```

I ran `Install-Module AzSK.ADO -Scope CurrentUser -AllowClobber -Force` to get the latest version and have imported the module using `Import-Module AzSK.ADO`

**Comment by murdockcrc** [comment]
Same issue here. Seems there is a missing dependency

**Comment by tasb** [comment]
I got the same issue here. any update on a solution?

**Comment by v-soukum** [comment]
Hello, 

Can you please share the exact repro steps, where you got this error.
Also can you please run below 2 commands on your powershell window and share the output.

- $PSVersionTable
- Get-Module -ListAvailable Az*

This will help us to investigate the issue.

**Comment by v-soukum** [comment]
Hello @MrAusnadian @murdockcrc @tasb,

Thank you for reaching out to us. We have identified the issue, this occures when powershell version 6.0 or 7.0 is used. We have taken a note of it and we will work to resolve it in future sprints. Till then please use powershell 5.1 version to run ADOScanner commands.

**Comment by wi-ry** [comment]
I'm guessing this is resolved or never going to be at this point.
